// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKTey5Y4J15kfK5nBm0baL2_0rQE70zks',
    appId: '1:180379522292:web:b96e2712e7c2c5e857baa1',
    messagingSenderId: '180379522292',
    projectId: 'doanltdd-c76a9',
    authDomain: 'doanltdd-c76a9.firebaseapp.com',
    storageBucket: 'doanltdd-c76a9.firebasestorage.app',
    measurementId: 'G-Y1S8BWH1WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTicxzFsO8s0kS-yz7WFVgRMYDSan2Lfo',
    appId: '1:180379522292:android:5f911f16211c8de657baa1',
    messagingSenderId: '180379522292',
    projectId: 'doanltdd-c76a9',
    storageBucket: 'doanltdd-c76a9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKTey5Y4J15kfK5nBm0baL2_0rQE70zks',
    appId: '1:180379522292:web:d82639963a3f88c957baa1',
    messagingSenderId: '180379522292',
    projectId: 'doanltdd-c76a9',
    authDomain: 'doanltdd-c76a9.firebaseapp.com',
    storageBucket: 'doanltdd-c76a9.firebasestorage.app',
    measurementId: 'G-L1P91YBH6B',
  );
}
