// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUghvOnymhKZved2gsrWYgX8z_3yooEmM',
    appId: '1:97435960842:web:c1ffa7e39d3a188116c1f3',
    messagingSenderId: '97435960842',
    projectId: 'doanltdd-3a47b',
    authDomain: 'doanltdd-3a47b.firebaseapp.com',
    storageBucket: 'doanltdd-3a47b.firebasestorage.app',
    measurementId: 'G-KVRDL73DX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiib-Kbe94SS_AEKvVVrlXF-9-e8Si50A',
    appId: '1:97435960842:android:8e16cfc844d12ec116c1f3',
    messagingSenderId: '97435960842',
    projectId: 'doanltdd-3a47b',
    storageBucket: 'doanltdd-3a47b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUghvOnymhKZved2gsrWYgX8z_3yooEmM',
    appId: '1:97435960842:web:c788d933e7e3085a16c1f3',
    messagingSenderId: '97435960842',
    projectId: 'doanltdd-3a47b',
    authDomain: 'doanltdd-3a47b.firebaseapp.com',
    storageBucket: 'doanltdd-3a47b.firebasestorage.app',
    measurementId: 'G-HVX1W0ZG0H',
  );

}